<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $products = [
            // Rings
            [
                'category_id' => 1,
                'title' => 'Diamond Solitaire Engagement Ring',
                'slug' => 'diamond-solitaire-engagement-ring',
                'description' => 'A classic and timeless diamond solitaire engagement ring featuring a brilliant-cut diamond set on a white gold band. Perfect for proposals and special moments.',
                'price' => 2500.00,
                'sale_price' => 2199.00,
                'sku' => 'RING-001',
                'stock_qty' => 15,
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/diamond-ring.jpg',
                'brand' => 'Luxe Jewelry',
                'tags' => 'engagement, diamond, ring, luxury',
            ],
            [
                'category_id' => 1,
                'title' => 'Gold Band Wedding Ring',
                'slug' => 'gold-band-wedding-ring',
                'description' => 'Elegant 18K gold wedding band with intricate detailing. A timeless piece for your special day.',
                'price' => 899.00,
                'sale_price' => 749.00,
                'sku' => 'RING-002',
                'stock_qty' => 20,
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/gold-ring.jpg',
                'brand' => 'Luxe Jewelry',
                'tags' => 'wedding, gold, ring, classic',
            ],
            // Necklaces
            [
                'category_id' => 2,
                'title' => 'Pearl Pendant Necklace',
                'slug' => 'pearl-pendant-necklace',
                'description' => 'Beautiful pearl pendant necklace with a delicate silver chain. Perfect for everyday wear or special occasions.',
                'price' => 450.00,
                'sale_price' => 349.00,
                'sku' => 'NECK-001',
                'stock_qty' => 25,
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/pearl-necklace.jpg',
                'brand' => 'Pearl Elegance',
                'tags' => 'pearl, necklace, pendant, elegant',
            ],
            [
                'category_id' => 2,
                'title' => 'Gold Chain Necklace',
                'slug' => 'gold-chain-necklace',
                'description' => 'Stunning 18K gold chain necklace with a sleek design. Versatile piece that goes with any outfit.',
                'price' => 599.00,
                'sale_price' => 499.00,
                'sku' => 'NECK-002',
                'stock_qty' => 18,
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/gold-chain.jpg',
                'brand' => 'Gold Luxe',
                'tags' => 'gold, chain, necklace, versatile',
            ],
            // Bracelets
            [
                'category_id' => 3,
                'title' => 'Tennis Bracelet Diamond',
                'slug' => 'tennis-bracelet-diamond',
                'description' => 'Exquisite tennis bracelet featuring brilliant-cut diamonds set in white gold. A statement piece for any occasion.',
                'price' => 1800.00,
                'sale_price' => 1499.00,
                'sku' => 'BRAC-001',
                'stock_qty' => 10,
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/tennis-bracelet.jpg',
                'brand' => 'Diamond Luxe',
                'tags' => 'diamond, bracelet, tennis, luxury',
            ],
            [
                'category_id' => 3,
                'title' => 'Silver Charm Bracelet',
                'slug' => 'silver-charm-bracelet',
                'description' => 'Elegant silver charm bracelet with interchangeable charms. Personalize your style with different charm combinations.',
                'price' => 299.00,
                'sale_price' => 199.00,
                'sku' => 'BRAC-002',
                'stock_qty' => 30,
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/charm-bracelet.jpg',
                'brand' => 'Charm Jewelry',
                'tags' => 'charm, bracelet, silver, personalized',
            ],
            // Earrings
            [
                'category_id' => 4,
                'title' => 'Diamond Stud Earrings',
                'slug' => 'diamond-stud-earrings',
                'description' => 'Classic diamond stud earrings featuring brilliant-cut diamonds in white gold settings. Perfect for everyday elegance.',
                'price' => 1200.00,
                'sale_price' => 999.00,
                'sku' => 'EAR-001',
                'stock_qty' => 22,
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/diamond-studs.jpg',
                'brand' => 'Diamond Luxe',
                'tags' => 'diamond, earrings, studs, elegant',
            ],
            [
                'category_id' => 4,
                'title' => 'Pearl Drop Earrings',
                'slug' => 'pearl-drop-earrings',
                'description' => 'Sophisticated pearl drop earrings with a graceful design. Ideal for formal events and special occasions.',
                'price' => 350.00,
                'sale_price' => 279.00,
                'sku' => 'EAR-002',
                'stock_qty' => 28,
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/pearl-earrings.jpg',
                'brand' => 'Pearl Elegance',
                'tags' => 'pearl, earrings, drop, formal',
            ],
            // Anklets
            [
                'category_id' => 5,
                'title' => 'Gold Anklet with Charms',
                'slug' => 'gold-anklet-with-charms',
                'description' => 'Delicate gold anklet adorned with charming pendants. Perfect for summer and beach season.',
                'price' => 199.00,
                'sale_price' => 149.00,
                'sku' => 'ANK-001',
                'stock_qty' => 35,
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/gold-anklet.jpg',
                'brand' => 'Charm Jewelry',
                'tags' => 'anklet, gold, charm, summer',
            ],
            [
                'category_id' => 5,
                'title' => 'Silver Chain Anklet',
                'slug' => 'silver-chain-anklet',
                'description' => 'Simple and elegant silver chain anklet. A versatile piece that complements any style.',
                'price' => 149.00,
                'sale_price' => 99.00,
                'sku' => 'ANK-002',
                'stock_qty' => 40,
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/silver-anklet.jpg',
                'brand' => 'Silver Luxe',
                'tags' => 'anklet, silver, chain, versatile',
            ],
            // Brooches
            [
                'category_id' => 6,
                'title' => 'Vintage Crystal Brooch',
                'slug' => 'vintage-crystal-brooch',
                'description' => 'Beautiful vintage-inspired crystal brooch with intricate detailing. A collector\'s piece for fashion enthusiasts.',
                'price' => 249.00,
                'sale_price' => 179.00,
                'sku' => 'BROO-001',
                'stock_qty' => 12,
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/vintage-brooch.jpg',
                'brand' => 'Vintage Luxe',
                'tags' => 'brooch, vintage, crystal, collectible',
            ],
            [
                'category_id' => 6,
                'title' => 'Gold Floral Brooch',
                'slug' => 'gold-floral-brooch',
                'description' => 'Elegant gold brooch with floral design. Perfect for adding a touch of sophistication to your outfit.',
                'price' => 299.00,
                'sale_price' => 229.00,
                'sku' => 'BROO-002',
                'stock_qty' => 16,
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/floral-brooch.jpg',
                'brand' => 'Gold Luxe',
                'tags' => 'brooch, gold, floral, elegant',
            ],
            // Watches
            [
                'category_id' => 7,
                'title' => 'Luxury Diamond Watch',
                'slug' => 'luxury-diamond-watch',
                'description' => 'Exquisite luxury watch featuring diamonds on the bezel. A timeless piece combining style and precision.',
                'price' => 3500.00,
                'sale_price' => 2999.00,
                'sku' => 'WATCH-001',
                'stock_qty' => 8,
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/diamond-watch.jpg',
                'brand' => 'Luxury Timepieces',
                'tags' => 'watch, diamond, luxury, timepiece',
            ],
            [
                'category_id' => 7,
                'title' => 'Gold Dress Watch',
                'slug' => 'gold-dress-watch',
                'description' => 'Elegant gold dress watch with a minimalist design. Perfect for formal occasions and everyday wear.',
                'price' => 899.00,
                'sale_price' => 749.00,
                'sku' => 'WATCH-002',
                'stock_qty' => 14,
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/gold-watch.jpg',
                'brand' => 'Gold Timepieces',
                'tags' => 'watch, gold, dress, elegant',
            ],
            // Body Jewelry
            [
                'category_id' => 8,
                'title' => 'Gold Nose Ring',
                'slug' => 'gold-nose-ring',
                'description' => 'Stylish gold nose ring available in various designs. Express your unique personality with this trendy piece.',
                'price' => 79.00,
                'sale_price' => 59.00,
                'sku' => 'BODY-001',
                'stock_qty' => 50,
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/nose-ring.jpg',
                'brand' => 'Body Luxe',
                'tags' => 'nose ring, body jewelry, gold, trendy',
            ],
            [
                'category_id' => 8,
                'title' => 'Crystal Belly Ring',
                'slug' => 'crystal-belly-ring',
                'description' => 'Sparkling crystal belly ring with a comfortable design. Perfect for body jewelry enthusiasts.',
                'price' => 49.00,
                'sale_price' => 39.00,
                'sku' => 'BODY-002',
                'stock_qty' => 45,
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/belly-ring.jpg',
                'brand' => 'Body Luxe',
                'tags' => 'belly ring, body jewelry, crystal, comfortable',
            ],
        ];

        foreach ($products as $product) {
            DB::table('products')->insert([
                'category_id' => $product['category_id'],
                'title' => $product['title'],
                'slug' => $product['slug'],
                'description' => $product['description'],
                'price' => $product['price'],
                'sale_price' => $product['sale_price'],
                'sku' => $product['sku'],
                'stock_qty' => $product['stock_qty'],
                'stock_status' => $product['stock_status'],
                'thumbnail' => $product['thumbnail'],
                'brand' => $product['brand'],
                'tags' => $product['tags'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
